// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/joaopedrosgs/loucore/ent/city"
	"github.com/joaopedrosgs/loucore/ent/construction"
	"github.com/joaopedrosgs/loucore/ent/predicate"
	"github.com/joaopedrosgs/loucore/ent/queueitem"
	"github.com/joaopedrosgs/loucore/ent/user"
)

// ConstructionUpdate is the builder for updating Construction entities.
type ConstructionUpdate struct {
	config
	hooks    []Hook
	mutation *ConstructionMutation
}

// Where adds a new predicate for the builder.
func (cu *ConstructionUpdate) Where(ps ...predicate.Construction) *ConstructionUpdate {
	cu.mutation.predicates = append(cu.mutation.predicates, ps...)
	return cu
}

// SetX sets the x field.
func (cu *ConstructionUpdate) SetX(i int) *ConstructionUpdate {
	cu.mutation.ResetX()
	cu.mutation.SetX(i)
	return cu
}

// AddX adds i to x.
func (cu *ConstructionUpdate) AddX(i int) *ConstructionUpdate {
	cu.mutation.AddX(i)
	return cu
}

// SetY sets the y field.
func (cu *ConstructionUpdate) SetY(i int) *ConstructionUpdate {
	cu.mutation.ResetY()
	cu.mutation.SetY(i)
	return cu
}

// AddY adds i to y.
func (cu *ConstructionUpdate) AddY(i int) *ConstructionUpdate {
	cu.mutation.AddY(i)
	return cu
}

// SetRawProduction sets the raw_production field.
func (cu *ConstructionUpdate) SetRawProduction(f float64) *ConstructionUpdate {
	cu.mutation.ResetRawProduction()
	cu.mutation.SetRawProduction(f)
	return cu
}

// SetNillableRawProduction sets the raw_production field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableRawProduction(f *float64) *ConstructionUpdate {
	if f != nil {
		cu.SetRawProduction(*f)
	}
	return cu
}

// AddRawProduction adds f to raw_production.
func (cu *ConstructionUpdate) AddRawProduction(f float64) *ConstructionUpdate {
	cu.mutation.AddRawProduction(f)
	return cu
}

// SetProduction sets the production field.
func (cu *ConstructionUpdate) SetProduction(f float64) *ConstructionUpdate {
	cu.mutation.ResetProduction()
	cu.mutation.SetProduction(f)
	return cu
}

// SetNillableProduction sets the production field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableProduction(f *float64) *ConstructionUpdate {
	if f != nil {
		cu.SetProduction(*f)
	}
	return cu
}

// AddProduction adds f to production.
func (cu *ConstructionUpdate) AddProduction(f float64) *ConstructionUpdate {
	cu.mutation.AddProduction(f)
	return cu
}

// SetType sets the type field.
func (cu *ConstructionUpdate) SetType(i int) *ConstructionUpdate {
	cu.mutation.ResetType()
	cu.mutation.SetType(i)
	return cu
}

// SetNillableType sets the type field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableType(i *int) *ConstructionUpdate {
	if i != nil {
		cu.SetType(*i)
	}
	return cu
}

// AddType adds i to type.
func (cu *ConstructionUpdate) AddType(i int) *ConstructionUpdate {
	cu.mutation.AddType(i)
	return cu
}

// SetLevel sets the level field.
func (cu *ConstructionUpdate) SetLevel(i int) *ConstructionUpdate {
	cu.mutation.ResetLevel()
	cu.mutation.SetLevel(i)
	return cu
}

// SetNillableLevel sets the level field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableLevel(i *int) *ConstructionUpdate {
	if i != nil {
		cu.SetLevel(*i)
	}
	return cu
}

// AddLevel adds i to level.
func (cu *ConstructionUpdate) AddLevel(i int) *ConstructionUpdate {
	cu.mutation.AddLevel(i)
	return cu
}

// SetModifier sets the modifier field.
func (cu *ConstructionUpdate) SetModifier(f float64) *ConstructionUpdate {
	cu.mutation.ResetModifier()
	cu.mutation.SetModifier(f)
	return cu
}

// SetNillableModifier sets the modifier field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableModifier(f *float64) *ConstructionUpdate {
	if f != nil {
		cu.SetModifier(*f)
	}
	return cu
}

// AddModifier adds f to modifier.
func (cu *ConstructionUpdate) AddModifier(f float64) *ConstructionUpdate {
	cu.mutation.AddModifier(f)
	return cu
}

// SetLastUpdated sets the last_updated field.
func (cu *ConstructionUpdate) SetLastUpdated(t time.Time) *ConstructionUpdate {
	cu.mutation.SetLastUpdated(t)
	return cu
}

// SetNillableLastUpdated sets the last_updated field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableLastUpdated(t *time.Time) *ConstructionUpdate {
	if t != nil {
		cu.SetLastUpdated(*t)
	}
	return cu
}

// SetNeedRefresh sets the need_refresh field.
func (cu *ConstructionUpdate) SetNeedRefresh(b bool) *ConstructionUpdate {
	cu.mutation.SetNeedRefresh(b)
	return cu
}

// SetNillableNeedRefresh sets the need_refresh field if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableNeedRefresh(b *bool) *ConstructionUpdate {
	if b != nil {
		cu.SetNeedRefresh(*b)
	}
	return cu
}

// SetCityID sets the city edge to City by id.
func (cu *ConstructionUpdate) SetCityID(id int) *ConstructionUpdate {
	cu.mutation.SetCityID(id)
	return cu
}

// SetCity sets the city edge to City.
func (cu *ConstructionUpdate) SetCity(c *City) *ConstructionUpdate {
	return cu.SetCityID(c.ID)
}

// SetOwnerID sets the owner edge to User by id.
func (cu *ConstructionUpdate) SetOwnerID(id int) *ConstructionUpdate {
	cu.mutation.SetOwnerID(id)
	return cu
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (cu *ConstructionUpdate) SetNillableOwnerID(id *int) *ConstructionUpdate {
	if id != nil {
		cu = cu.SetOwnerID(*id)
	}
	return cu
}

// SetOwner sets the owner edge to User.
func (cu *ConstructionUpdate) SetOwner(u *User) *ConstructionUpdate {
	return cu.SetOwnerID(u.ID)
}

// AddQueueIDs adds the queue edge to QueueItem by ids.
func (cu *ConstructionUpdate) AddQueueIDs(ids ...int) *ConstructionUpdate {
	cu.mutation.AddQueueIDs(ids...)
	return cu
}

// AddQueue adds the queue edges to QueueItem.
func (cu *ConstructionUpdate) AddQueue(q ...*QueueItem) *ConstructionUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return cu.AddQueueIDs(ids...)
}

// AddAffectIDs adds the affects edge to Construction by ids.
func (cu *ConstructionUpdate) AddAffectIDs(ids ...int) *ConstructionUpdate {
	cu.mutation.AddAffectIDs(ids...)
	return cu
}

// AddAffects adds the affects edges to Construction.
func (cu *ConstructionUpdate) AddAffects(c ...*Construction) *ConstructionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddAffectIDs(ids...)
}

// AddAffectedByIDs adds the affected_by edge to Construction by ids.
func (cu *ConstructionUpdate) AddAffectedByIDs(ids ...int) *ConstructionUpdate {
	cu.mutation.AddAffectedByIDs(ids...)
	return cu
}

// AddAffectedBy adds the affected_by edges to Construction.
func (cu *ConstructionUpdate) AddAffectedBy(c ...*Construction) *ConstructionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddAffectedByIDs(ids...)
}

// Mutation returns the ConstructionMutation object of the builder.
func (cu *ConstructionUpdate) Mutation() *ConstructionMutation {
	return cu.mutation
}

// ClearCity clears the "city" edge to type City.
func (cu *ConstructionUpdate) ClearCity() *ConstructionUpdate {
	cu.mutation.ClearCity()
	return cu
}

// ClearOwner clears the "owner" edge to type User.
func (cu *ConstructionUpdate) ClearOwner() *ConstructionUpdate {
	cu.mutation.ClearOwner()
	return cu
}

// ClearQueue clears all "queue" edges to type QueueItem.
func (cu *ConstructionUpdate) ClearQueue() *ConstructionUpdate {
	cu.mutation.ClearQueue()
	return cu
}

// RemoveQueueIDs removes the queue edge to QueueItem by ids.
func (cu *ConstructionUpdate) RemoveQueueIDs(ids ...int) *ConstructionUpdate {
	cu.mutation.RemoveQueueIDs(ids...)
	return cu
}

// RemoveQueue removes queue edges to QueueItem.
func (cu *ConstructionUpdate) RemoveQueue(q ...*QueueItem) *ConstructionUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return cu.RemoveQueueIDs(ids...)
}

// ClearAffects clears all "affects" edges to type Construction.
func (cu *ConstructionUpdate) ClearAffects() *ConstructionUpdate {
	cu.mutation.ClearAffects()
	return cu
}

// RemoveAffectIDs removes the affects edge to Construction by ids.
func (cu *ConstructionUpdate) RemoveAffectIDs(ids ...int) *ConstructionUpdate {
	cu.mutation.RemoveAffectIDs(ids...)
	return cu
}

// RemoveAffects removes affects edges to Construction.
func (cu *ConstructionUpdate) RemoveAffects(c ...*Construction) *ConstructionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveAffectIDs(ids...)
}

// ClearAffectedBy clears all "affected_by" edges to type Construction.
func (cu *ConstructionUpdate) ClearAffectedBy() *ConstructionUpdate {
	cu.mutation.ClearAffectedBy()
	return cu
}

// RemoveAffectedByIDs removes the affected_by edge to Construction by ids.
func (cu *ConstructionUpdate) RemoveAffectedByIDs(ids ...int) *ConstructionUpdate {
	cu.mutation.RemoveAffectedByIDs(ids...)
	return cu
}

// RemoveAffectedBy removes affected_by edges to Construction.
func (cu *ConstructionUpdate) RemoveAffectedBy(c ...*Construction) *ConstructionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveAffectedByIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *ConstructionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConstructionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ConstructionUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ConstructionUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ConstructionUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ConstructionUpdate) check() error {
	if _, ok := cu.mutation.CityID(); cu.mutation.CityCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"city\"")
	}
	return nil
}

func (cu *ConstructionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   construction.Table,
			Columns: construction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: construction.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.X(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldX,
		})
	}
	if value, ok := cu.mutation.AddedX(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldX,
		})
	}
	if value, ok := cu.mutation.Y(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldY,
		})
	}
	if value, ok := cu.mutation.AddedY(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldY,
		})
	}
	if value, ok := cu.mutation.RawProduction(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldRawProduction,
		})
	}
	if value, ok := cu.mutation.AddedRawProduction(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldRawProduction,
		})
	}
	if value, ok := cu.mutation.Production(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldProduction,
		})
	}
	if value, ok := cu.mutation.AddedProduction(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldProduction,
		})
	}
	if value, ok := cu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldType,
		})
	}
	if value, ok := cu.mutation.AddedType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldType,
		})
	}
	if value, ok := cu.mutation.Level(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldLevel,
		})
	}
	if value, ok := cu.mutation.AddedLevel(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldLevel,
		})
	}
	if value, ok := cu.mutation.Modifier(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldModifier,
		})
	}
	if value, ok := cu.mutation.AddedModifier(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldModifier,
		})
	}
	if value, ok := cu.mutation.LastUpdated(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: construction.FieldLastUpdated,
		})
	}
	if value, ok := cu.mutation.NeedRefresh(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: construction.FieldNeedRefresh,
		})
	}
	if cu.mutation.CityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.CityTable,
			Columns: []string{construction.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.CityTable,
			Columns: []string{construction.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.OwnerTable,
			Columns: []string{construction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.OwnerTable,
			Columns: []string{construction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queueitem.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedQueueIDs(); len(nodes) > 0 && !cu.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queueitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queueitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.AffectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   construction.AffectsTable,
			Columns: construction.AffectsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedAffectsIDs(); len(nodes) > 0 && !cu.mutation.AffectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   construction.AffectsTable,
			Columns: construction.AffectsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AffectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   construction.AffectsTable,
			Columns: construction.AffectsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.AffectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   construction.AffectedByTable,
			Columns: construction.AffectedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedAffectedByIDs(); len(nodes) > 0 && !cu.mutation.AffectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   construction.AffectedByTable,
			Columns: construction.AffectedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AffectedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   construction.AffectedByTable,
			Columns: construction.AffectedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{construction.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ConstructionUpdateOne is the builder for updating a single Construction entity.
type ConstructionUpdateOne struct {
	config
	hooks    []Hook
	mutation *ConstructionMutation
}

// SetX sets the x field.
func (cuo *ConstructionUpdateOne) SetX(i int) *ConstructionUpdateOne {
	cuo.mutation.ResetX()
	cuo.mutation.SetX(i)
	return cuo
}

// AddX adds i to x.
func (cuo *ConstructionUpdateOne) AddX(i int) *ConstructionUpdateOne {
	cuo.mutation.AddX(i)
	return cuo
}

// SetY sets the y field.
func (cuo *ConstructionUpdateOne) SetY(i int) *ConstructionUpdateOne {
	cuo.mutation.ResetY()
	cuo.mutation.SetY(i)
	return cuo
}

// AddY adds i to y.
func (cuo *ConstructionUpdateOne) AddY(i int) *ConstructionUpdateOne {
	cuo.mutation.AddY(i)
	return cuo
}

// SetRawProduction sets the raw_production field.
func (cuo *ConstructionUpdateOne) SetRawProduction(f float64) *ConstructionUpdateOne {
	cuo.mutation.ResetRawProduction()
	cuo.mutation.SetRawProduction(f)
	return cuo
}

// SetNillableRawProduction sets the raw_production field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableRawProduction(f *float64) *ConstructionUpdateOne {
	if f != nil {
		cuo.SetRawProduction(*f)
	}
	return cuo
}

// AddRawProduction adds f to raw_production.
func (cuo *ConstructionUpdateOne) AddRawProduction(f float64) *ConstructionUpdateOne {
	cuo.mutation.AddRawProduction(f)
	return cuo
}

// SetProduction sets the production field.
func (cuo *ConstructionUpdateOne) SetProduction(f float64) *ConstructionUpdateOne {
	cuo.mutation.ResetProduction()
	cuo.mutation.SetProduction(f)
	return cuo
}

// SetNillableProduction sets the production field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableProduction(f *float64) *ConstructionUpdateOne {
	if f != nil {
		cuo.SetProduction(*f)
	}
	return cuo
}

// AddProduction adds f to production.
func (cuo *ConstructionUpdateOne) AddProduction(f float64) *ConstructionUpdateOne {
	cuo.mutation.AddProduction(f)
	return cuo
}

// SetType sets the type field.
func (cuo *ConstructionUpdateOne) SetType(i int) *ConstructionUpdateOne {
	cuo.mutation.ResetType()
	cuo.mutation.SetType(i)
	return cuo
}

// SetNillableType sets the type field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableType(i *int) *ConstructionUpdateOne {
	if i != nil {
		cuo.SetType(*i)
	}
	return cuo
}

// AddType adds i to type.
func (cuo *ConstructionUpdateOne) AddType(i int) *ConstructionUpdateOne {
	cuo.mutation.AddType(i)
	return cuo
}

// SetLevel sets the level field.
func (cuo *ConstructionUpdateOne) SetLevel(i int) *ConstructionUpdateOne {
	cuo.mutation.ResetLevel()
	cuo.mutation.SetLevel(i)
	return cuo
}

// SetNillableLevel sets the level field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableLevel(i *int) *ConstructionUpdateOne {
	if i != nil {
		cuo.SetLevel(*i)
	}
	return cuo
}

// AddLevel adds i to level.
func (cuo *ConstructionUpdateOne) AddLevel(i int) *ConstructionUpdateOne {
	cuo.mutation.AddLevel(i)
	return cuo
}

// SetModifier sets the modifier field.
func (cuo *ConstructionUpdateOne) SetModifier(f float64) *ConstructionUpdateOne {
	cuo.mutation.ResetModifier()
	cuo.mutation.SetModifier(f)
	return cuo
}

// SetNillableModifier sets the modifier field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableModifier(f *float64) *ConstructionUpdateOne {
	if f != nil {
		cuo.SetModifier(*f)
	}
	return cuo
}

// AddModifier adds f to modifier.
func (cuo *ConstructionUpdateOne) AddModifier(f float64) *ConstructionUpdateOne {
	cuo.mutation.AddModifier(f)
	return cuo
}

// SetLastUpdated sets the last_updated field.
func (cuo *ConstructionUpdateOne) SetLastUpdated(t time.Time) *ConstructionUpdateOne {
	cuo.mutation.SetLastUpdated(t)
	return cuo
}

// SetNillableLastUpdated sets the last_updated field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableLastUpdated(t *time.Time) *ConstructionUpdateOne {
	if t != nil {
		cuo.SetLastUpdated(*t)
	}
	return cuo
}

// SetNeedRefresh sets the need_refresh field.
func (cuo *ConstructionUpdateOne) SetNeedRefresh(b bool) *ConstructionUpdateOne {
	cuo.mutation.SetNeedRefresh(b)
	return cuo
}

// SetNillableNeedRefresh sets the need_refresh field if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableNeedRefresh(b *bool) *ConstructionUpdateOne {
	if b != nil {
		cuo.SetNeedRefresh(*b)
	}
	return cuo
}

// SetCityID sets the city edge to City by id.
func (cuo *ConstructionUpdateOne) SetCityID(id int) *ConstructionUpdateOne {
	cuo.mutation.SetCityID(id)
	return cuo
}

// SetCity sets the city edge to City.
func (cuo *ConstructionUpdateOne) SetCity(c *City) *ConstructionUpdateOne {
	return cuo.SetCityID(c.ID)
}

// SetOwnerID sets the owner edge to User by id.
func (cuo *ConstructionUpdateOne) SetOwnerID(id int) *ConstructionUpdateOne {
	cuo.mutation.SetOwnerID(id)
	return cuo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (cuo *ConstructionUpdateOne) SetNillableOwnerID(id *int) *ConstructionUpdateOne {
	if id != nil {
		cuo = cuo.SetOwnerID(*id)
	}
	return cuo
}

// SetOwner sets the owner edge to User.
func (cuo *ConstructionUpdateOne) SetOwner(u *User) *ConstructionUpdateOne {
	return cuo.SetOwnerID(u.ID)
}

// AddQueueIDs adds the queue edge to QueueItem by ids.
func (cuo *ConstructionUpdateOne) AddQueueIDs(ids ...int) *ConstructionUpdateOne {
	cuo.mutation.AddQueueIDs(ids...)
	return cuo
}

// AddQueue adds the queue edges to QueueItem.
func (cuo *ConstructionUpdateOne) AddQueue(q ...*QueueItem) *ConstructionUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return cuo.AddQueueIDs(ids...)
}

// AddAffectIDs adds the affects edge to Construction by ids.
func (cuo *ConstructionUpdateOne) AddAffectIDs(ids ...int) *ConstructionUpdateOne {
	cuo.mutation.AddAffectIDs(ids...)
	return cuo
}

// AddAffects adds the affects edges to Construction.
func (cuo *ConstructionUpdateOne) AddAffects(c ...*Construction) *ConstructionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddAffectIDs(ids...)
}

// AddAffectedByIDs adds the affected_by edge to Construction by ids.
func (cuo *ConstructionUpdateOne) AddAffectedByIDs(ids ...int) *ConstructionUpdateOne {
	cuo.mutation.AddAffectedByIDs(ids...)
	return cuo
}

// AddAffectedBy adds the affected_by edges to Construction.
func (cuo *ConstructionUpdateOne) AddAffectedBy(c ...*Construction) *ConstructionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddAffectedByIDs(ids...)
}

// Mutation returns the ConstructionMutation object of the builder.
func (cuo *ConstructionUpdateOne) Mutation() *ConstructionMutation {
	return cuo.mutation
}

// ClearCity clears the "city" edge to type City.
func (cuo *ConstructionUpdateOne) ClearCity() *ConstructionUpdateOne {
	cuo.mutation.ClearCity()
	return cuo
}

// ClearOwner clears the "owner" edge to type User.
func (cuo *ConstructionUpdateOne) ClearOwner() *ConstructionUpdateOne {
	cuo.mutation.ClearOwner()
	return cuo
}

// ClearQueue clears all "queue" edges to type QueueItem.
func (cuo *ConstructionUpdateOne) ClearQueue() *ConstructionUpdateOne {
	cuo.mutation.ClearQueue()
	return cuo
}

// RemoveQueueIDs removes the queue edge to QueueItem by ids.
func (cuo *ConstructionUpdateOne) RemoveQueueIDs(ids ...int) *ConstructionUpdateOne {
	cuo.mutation.RemoveQueueIDs(ids...)
	return cuo
}

// RemoveQueue removes queue edges to QueueItem.
func (cuo *ConstructionUpdateOne) RemoveQueue(q ...*QueueItem) *ConstructionUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return cuo.RemoveQueueIDs(ids...)
}

// ClearAffects clears all "affects" edges to type Construction.
func (cuo *ConstructionUpdateOne) ClearAffects() *ConstructionUpdateOne {
	cuo.mutation.ClearAffects()
	return cuo
}

// RemoveAffectIDs removes the affects edge to Construction by ids.
func (cuo *ConstructionUpdateOne) RemoveAffectIDs(ids ...int) *ConstructionUpdateOne {
	cuo.mutation.RemoveAffectIDs(ids...)
	return cuo
}

// RemoveAffects removes affects edges to Construction.
func (cuo *ConstructionUpdateOne) RemoveAffects(c ...*Construction) *ConstructionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveAffectIDs(ids...)
}

// ClearAffectedBy clears all "affected_by" edges to type Construction.
func (cuo *ConstructionUpdateOne) ClearAffectedBy() *ConstructionUpdateOne {
	cuo.mutation.ClearAffectedBy()
	return cuo
}

// RemoveAffectedByIDs removes the affected_by edge to Construction by ids.
func (cuo *ConstructionUpdateOne) RemoveAffectedByIDs(ids ...int) *ConstructionUpdateOne {
	cuo.mutation.RemoveAffectedByIDs(ids...)
	return cuo
}

// RemoveAffectedBy removes affected_by edges to Construction.
func (cuo *ConstructionUpdateOne) RemoveAffectedBy(c ...*Construction) *ConstructionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveAffectedByIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *ConstructionUpdateOne) Save(ctx context.Context) (*Construction, error) {
	var (
		err  error
		node *Construction
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConstructionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ConstructionUpdateOne) SaveX(ctx context.Context) *Construction {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ConstructionUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ConstructionUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ConstructionUpdateOne) check() error {
	if _, ok := cuo.mutation.CityID(); cuo.mutation.CityCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"city\"")
	}
	return nil
}

func (cuo *ConstructionUpdateOne) sqlSave(ctx context.Context) (_node *Construction, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   construction.Table,
			Columns: construction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: construction.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Construction.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.X(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldX,
		})
	}
	if value, ok := cuo.mutation.AddedX(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldX,
		})
	}
	if value, ok := cuo.mutation.Y(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldY,
		})
	}
	if value, ok := cuo.mutation.AddedY(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldY,
		})
	}
	if value, ok := cuo.mutation.RawProduction(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldRawProduction,
		})
	}
	if value, ok := cuo.mutation.AddedRawProduction(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldRawProduction,
		})
	}
	if value, ok := cuo.mutation.Production(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldProduction,
		})
	}
	if value, ok := cuo.mutation.AddedProduction(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldProduction,
		})
	}
	if value, ok := cuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldType,
		})
	}
	if value, ok := cuo.mutation.AddedType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldType,
		})
	}
	if value, ok := cuo.mutation.Level(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldLevel,
		})
	}
	if value, ok := cuo.mutation.AddedLevel(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: construction.FieldLevel,
		})
	}
	if value, ok := cuo.mutation.Modifier(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldModifier,
		})
	}
	if value, ok := cuo.mutation.AddedModifier(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: construction.FieldModifier,
		})
	}
	if value, ok := cuo.mutation.LastUpdated(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: construction.FieldLastUpdated,
		})
	}
	if value, ok := cuo.mutation.NeedRefresh(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: construction.FieldNeedRefresh,
		})
	}
	if cuo.mutation.CityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.CityTable,
			Columns: []string{construction.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.CityTable,
			Columns: []string{construction.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.OwnerTable,
			Columns: []string{construction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.OwnerTable,
			Columns: []string{construction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queueitem.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedQueueIDs(); len(nodes) > 0 && !cuo.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queueitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queueitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.AffectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   construction.AffectsTable,
			Columns: construction.AffectsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedAffectsIDs(); len(nodes) > 0 && !cuo.mutation.AffectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   construction.AffectsTable,
			Columns: construction.AffectsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AffectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   construction.AffectsTable,
			Columns: construction.AffectsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.AffectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   construction.AffectedByTable,
			Columns: construction.AffectedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedAffectedByIDs(); len(nodes) > 0 && !cuo.mutation.AffectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   construction.AffectedByTable,
			Columns: construction.AffectedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AffectedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   construction.AffectedByTable,
			Columns: construction.AffectedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Construction{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{construction.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
