// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/joaopedrosgs/loucore/ent/predicate"
	"github.com/joaopedrosgs/loucore/ent/queueitem"
)

// QueueItemDelete is the builder for deleting a QueueItem entity.
type QueueItemDelete struct {
	config
	hooks      []Hook
	mutation   *QueueItemMutation
	predicates []predicate.QueueItem
}

// Where adds a new predicate to the delete builder.
func (qid *QueueItemDelete) Where(ps ...predicate.QueueItem) *QueueItemDelete {
	qid.predicates = append(qid.predicates, ps...)
	return qid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qid *QueueItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qid.hooks) == 0 {
		affected, err = qid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QueueItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qid.mutation = mutation
			affected, err = qid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qid.hooks) - 1; i >= 0; i-- {
			mut = qid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qid *QueueItemDelete) ExecX(ctx context.Context) int {
	n, err := qid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qid *QueueItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: queueitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: queueitem.FieldID,
			},
		},
	}
	if ps := qid.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, qid.driver, _spec)
}

// QueueItemDeleteOne is the builder for deleting a single QueueItem entity.
type QueueItemDeleteOne struct {
	qid *QueueItemDelete
}

// Exec executes the deletion query.
func (qido *QueueItemDeleteOne) Exec(ctx context.Context) error {
	n, err := qido.qid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{queueitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qido *QueueItemDeleteOne) ExecX(ctx context.Context) {
	qido.qid.ExecX(ctx)
}
