// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/joaopedrosgs/loucore/ent/city"
	"github.com/joaopedrosgs/loucore/ent/construction"
	"github.com/joaopedrosgs/loucore/ent/predicate"
	"github.com/joaopedrosgs/loucore/ent/queueitem"
	"github.com/joaopedrosgs/loucore/ent/user"
)

// QueueItemQuery is the builder for querying QueueItem entities.
type QueueItemQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.QueueItem
	// eager-loading edges.
	withOwner        *UserQuery
	withCity         *CityQuery
	withConstruction *ConstructionQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (qiq *QueueItemQuery) Where(ps ...predicate.QueueItem) *QueueItemQuery {
	qiq.predicates = append(qiq.predicates, ps...)
	return qiq
}

// Limit adds a limit step to the query.
func (qiq *QueueItemQuery) Limit(limit int) *QueueItemQuery {
	qiq.limit = &limit
	return qiq
}

// Offset adds an offset step to the query.
func (qiq *QueueItemQuery) Offset(offset int) *QueueItemQuery {
	qiq.offset = &offset
	return qiq
}

// Order adds an order step to the query.
func (qiq *QueueItemQuery) Order(o ...OrderFunc) *QueueItemQuery {
	qiq.order = append(qiq.order, o...)
	return qiq
}

// QueryOwner chains the current query on the owner edge.
func (qiq *QueueItemQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: qiq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qiq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queueitem.Table, queueitem.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, queueitem.OwnerTable, queueitem.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(qiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCity chains the current query on the city edge.
func (qiq *QueueItemQuery) QueryCity() *CityQuery {
	query := &CityQuery{config: qiq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qiq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queueitem.Table, queueitem.FieldID, selector),
			sqlgraph.To(city.Table, city.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, queueitem.CityTable, queueitem.CityColumn),
		)
		fromU = sqlgraph.SetNeighbors(qiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConstruction chains the current query on the construction edge.
func (qiq *QueueItemQuery) QueryConstruction() *ConstructionQuery {
	query := &ConstructionQuery{config: qiq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qiq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queueitem.Table, queueitem.FieldID, selector),
			sqlgraph.To(construction.Table, construction.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, queueitem.ConstructionTable, queueitem.ConstructionColumn),
		)
		fromU = sqlgraph.SetNeighbors(qiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QueueItem entity in the query. Returns *NotFoundError when no queueitem was found.
func (qiq *QueueItemQuery) First(ctx context.Context) (*QueueItem, error) {
	nodes, err := qiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{queueitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qiq *QueueItemQuery) FirstX(ctx context.Context) *QueueItem {
	node, err := qiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QueueItem id in the query. Returns *NotFoundError when no id was found.
func (qiq *QueueItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{queueitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qiq *QueueItemQuery) FirstIDX(ctx context.Context) int {
	id, err := qiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only QueueItem entity in the query, returns an error if not exactly one entity was returned.
func (qiq *QueueItemQuery) Only(ctx context.Context) (*QueueItem, error) {
	nodes, err := qiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{queueitem.Label}
	default:
		return nil, &NotSingularError{queueitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qiq *QueueItemQuery) OnlyX(ctx context.Context) *QueueItem {
	node, err := qiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only QueueItem id in the query, returns an error if not exactly one id was returned.
func (qiq *QueueItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = &NotSingularError{queueitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qiq *QueueItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := qiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QueueItems.
func (qiq *QueueItemQuery) All(ctx context.Context) ([]*QueueItem, error) {
	if err := qiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return qiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (qiq *QueueItemQuery) AllX(ctx context.Context) []*QueueItem {
	nodes, err := qiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QueueItem ids.
func (qiq *QueueItemQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := qiq.Select(queueitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qiq *QueueItemQuery) IDsX(ctx context.Context) []int {
	ids, err := qiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qiq *QueueItemQuery) Count(ctx context.Context) (int, error) {
	if err := qiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return qiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (qiq *QueueItemQuery) CountX(ctx context.Context) int {
	count, err := qiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qiq *QueueItemQuery) Exist(ctx context.Context) (bool, error) {
	if err := qiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return qiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (qiq *QueueItemQuery) ExistX(ctx context.Context) bool {
	exist, err := qiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qiq *QueueItemQuery) Clone() *QueueItemQuery {
	if qiq == nil {
		return nil
	}
	return &QueueItemQuery{
		config:           qiq.config,
		limit:            qiq.limit,
		offset:           qiq.offset,
		order:            append([]OrderFunc{}, qiq.order...),
		unique:           append([]string{}, qiq.unique...),
		predicates:       append([]predicate.QueueItem{}, qiq.predicates...),
		withOwner:        qiq.withOwner.Clone(),
		withCity:         qiq.withCity.Clone(),
		withConstruction: qiq.withConstruction.Clone(),
		// clone intermediate query.
		sql:  qiq.sql.Clone(),
		path: qiq.path,
	}
}

//  WithOwner tells the query-builder to eager-loads the nodes that are connected to
// the "owner" edge. The optional arguments used to configure the query builder of the edge.
func (qiq *QueueItemQuery) WithOwner(opts ...func(*UserQuery)) *QueueItemQuery {
	query := &UserQuery{config: qiq.config}
	for _, opt := range opts {
		opt(query)
	}
	qiq.withOwner = query
	return qiq
}

//  WithCity tells the query-builder to eager-loads the nodes that are connected to
// the "city" edge. The optional arguments used to configure the query builder of the edge.
func (qiq *QueueItemQuery) WithCity(opts ...func(*CityQuery)) *QueueItemQuery {
	query := &CityQuery{config: qiq.config}
	for _, opt := range opts {
		opt(query)
	}
	qiq.withCity = query
	return qiq
}

//  WithConstruction tells the query-builder to eager-loads the nodes that are connected to
// the "construction" edge. The optional arguments used to configure the query builder of the edge.
func (qiq *QueueItemQuery) WithConstruction(opts ...func(*ConstructionQuery)) *QueueItemQuery {
	query := &ConstructionQuery{config: qiq.config}
	for _, opt := range opts {
		opt(query)
	}
	qiq.withConstruction = query
	return qiq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Duration int `json:"duration,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QueueItem.Query().
//		GroupBy(queueitem.FieldDuration).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (qiq *QueueItemQuery) GroupBy(field string, fields ...string) *QueueItemGroupBy {
	group := &QueueItemGroupBy{config: qiq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := qiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return qiq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Duration int `json:"duration,omitempty"`
//	}
//
//	client.QueueItem.Query().
//		Select(queueitem.FieldDuration).
//		Scan(ctx, &v)
//
func (qiq *QueueItemQuery) Select(field string, fields ...string) *QueueItemSelect {
	selector := &QueueItemSelect{config: qiq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := qiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return qiq.sqlQuery(), nil
	}
	return selector
}

func (qiq *QueueItemQuery) prepareQuery(ctx context.Context) error {
	if qiq.path != nil {
		prev, err := qiq.path(ctx)
		if err != nil {
			return err
		}
		qiq.sql = prev
	}
	return nil
}

func (qiq *QueueItemQuery) sqlAll(ctx context.Context) ([]*QueueItem, error) {
	var (
		nodes       = []*QueueItem{}
		withFKs     = qiq.withFKs
		_spec       = qiq.querySpec()
		loadedTypes = [3]bool{
			qiq.withOwner != nil,
			qiq.withCity != nil,
			qiq.withConstruction != nil,
		}
	)
	if qiq.withOwner != nil || qiq.withCity != nil || qiq.withConstruction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, queueitem.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &QueueItem{config: qiq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, qiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := qiq.withOwner; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*QueueItem)
		for i := range nodes {
			if fk := nodes[i].user_queue; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_queue" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	if query := qiq.withCity; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*QueueItem)
		for i := range nodes {
			if fk := nodes[i].city_queue; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(city.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "city_queue" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.City = n
			}
		}
	}

	if query := qiq.withConstruction; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*QueueItem)
		for i := range nodes {
			if fk := nodes[i].construction_queue; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(construction.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "construction_queue" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Construction = n
			}
		}
	}

	return nodes, nil
}

func (qiq *QueueItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qiq.querySpec()
	return sqlgraph.CountNodes(ctx, qiq.driver, _spec)
}

func (qiq *QueueItemQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := qiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (qiq *QueueItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   queueitem.Table,
			Columns: queueitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: queueitem.FieldID,
			},
		},
		From:   qiq.sql,
		Unique: true,
	}
	if ps := qiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, queueitem.ValidColumn)
			}
		}
	}
	return _spec
}

func (qiq *QueueItemQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(qiq.driver.Dialect())
	t1 := builder.Table(queueitem.Table)
	selector := builder.Select(t1.Columns(queueitem.Columns...)...).From(t1)
	if qiq.sql != nil {
		selector = qiq.sql
		selector.Select(selector.Columns(queueitem.Columns...)...)
	}
	for _, p := range qiq.predicates {
		p(selector)
	}
	for _, p := range qiq.order {
		p(selector, queueitem.ValidColumn)
	}
	if offset := qiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QueueItemGroupBy is the builder for group-by QueueItem entities.
type QueueItemGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qigb *QueueItemGroupBy) Aggregate(fns ...AggregateFunc) *QueueItemGroupBy {
	qigb.fns = append(qigb.fns, fns...)
	return qigb
}

// Scan applies the group-by query and scan the result into the given value.
func (qigb *QueueItemGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := qigb.path(ctx)
	if err != nil {
		return err
	}
	qigb.sql = query
	return qigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (qigb *QueueItemGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := qigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(qigb.fields) > 1 {
		return nil, errors.New("ent: QueueItemGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := qigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (qigb *QueueItemGroupBy) StringsX(ctx context.Context) []string {
	v, err := qigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = qigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (qigb *QueueItemGroupBy) StringX(ctx context.Context) string {
	v, err := qigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(qigb.fields) > 1 {
		return nil, errors.New("ent: QueueItemGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := qigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (qigb *QueueItemGroupBy) IntsX(ctx context.Context) []int {
	v, err := qigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = qigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (qigb *QueueItemGroupBy) IntX(ctx context.Context) int {
	v, err := qigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(qigb.fields) > 1 {
		return nil, errors.New("ent: QueueItemGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := qigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (qigb *QueueItemGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := qigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = qigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (qigb *QueueItemGroupBy) Float64X(ctx context.Context) float64 {
	v, err := qigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(qigb.fields) > 1 {
		return nil, errors.New("ent: QueueItemGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := qigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (qigb *QueueItemGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := qigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (qigb *QueueItemGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = qigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (qigb *QueueItemGroupBy) BoolX(ctx context.Context) bool {
	v, err := qigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (qigb *QueueItemGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range qigb.fields {
		if !queueitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := qigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (qigb *QueueItemGroupBy) sqlQuery() *sql.Selector {
	selector := qigb.sql
	columns := make([]string, 0, len(qigb.fields)+len(qigb.fns))
	columns = append(columns, qigb.fields...)
	for _, fn := range qigb.fns {
		columns = append(columns, fn(selector, queueitem.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(qigb.fields...)
}

// QueueItemSelect is the builder for select fields of QueueItem entities.
type QueueItemSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (qis *QueueItemSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := qis.path(ctx)
	if err != nil {
		return err
	}
	qis.sql = query
	return qis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (qis *QueueItemSelect) ScanX(ctx context.Context, v interface{}) {
	if err := qis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Strings(ctx context.Context) ([]string, error) {
	if len(qis.fields) > 1 {
		return nil, errors.New("ent: QueueItemSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := qis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (qis *QueueItemSelect) StringsX(ctx context.Context) []string {
	v, err := qis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = qis.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (qis *QueueItemSelect) StringX(ctx context.Context) string {
	v, err := qis.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Ints(ctx context.Context) ([]int, error) {
	if len(qis.fields) > 1 {
		return nil, errors.New("ent: QueueItemSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := qis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (qis *QueueItemSelect) IntsX(ctx context.Context) []int {
	v, err := qis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = qis.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (qis *QueueItemSelect) IntX(ctx context.Context) int {
	v, err := qis.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(qis.fields) > 1 {
		return nil, errors.New("ent: QueueItemSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := qis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (qis *QueueItemSelect) Float64sX(ctx context.Context) []float64 {
	v, err := qis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = qis.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (qis *QueueItemSelect) Float64X(ctx context.Context) float64 {
	v, err := qis.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(qis.fields) > 1 {
		return nil, errors.New("ent: QueueItemSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := qis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (qis *QueueItemSelect) BoolsX(ctx context.Context) []bool {
	v, err := qis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (qis *QueueItemSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = qis.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{queueitem.Label}
	default:
		err = fmt.Errorf("ent: QueueItemSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (qis *QueueItemSelect) BoolX(ctx context.Context) bool {
	v, err := qis.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (qis *QueueItemSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range qis.fields {
		if !queueitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := qis.sqlQuery().Query()
	if err := qis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (qis *QueueItemSelect) sqlQuery() sql.Querier {
	selector := qis.sql
	selector.Select(selector.Columns(qis.fields...)...)
	return selector
}
